# Generated by Django 3.1.2 on 2020-10-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=150)),
                ('desc', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='uploads/cafe/')),
                ('address', models.TextField(max_length=250)),
                ('desc', models.TextField(max_length=250)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.province')),
            ],
        ),
    ]
